# -*- coding: utf-8 -*-
"""cartesian_product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDeYvyzXhARrD4Ugysgm3ht0DBnhDBHS
"""

# ============================================================================
# Program:    create_cartesian.py (Google Colab)
# Purpose:    Create all combinations of determination level values
#             from one year to the next year using a Cartesian product.
# ============================================================================

import pandas as pd

# ===============================================================
# SECTION 1: Dataset #1 - 2019 Determination Levels (DL2019)
# ===============================================================
data_2019 = {
    'DL': ['DL0', 'DL1', 'DL2', 'DL3', 'DL4'],
    'DL2019': [0, 1, 2, 3, 4]
}
a_table = pd.DataFrame(data_2019)

# ===============================================================
# SECTION 2: Dataset #2 - 2020 Determination Levels (DL2020)
# ===============================================================
data_2020 = {
    'DL': ['DL1', 'DL2', 'DL3', 'DL4'],
    'DL2020': [1, 2, 3, 4]
}
b_table = pd.DataFrame(data_2020)

# ===============================================================
# SECTION 3: Generate Cartesian Product of DL2019 × DL2020
# ===============================================================
# Perform Cartesian product using a dummy key
a_table['_key'] = 1
b_table['_key'] = 1
merged = pd.merge(a_table, b_table, on='_key')
cartesian_dl = merged.drop(columns=['_key', 'DL_x', 'DL_y'])

# ===============================================================
# Display and Export Result
# ===============================================================
from datetime import datetime
from google.colab import files

print("▶ Cartesian Product of 2019 and 2020 DLs:")
display(cartesian_dl)

# Export to Excel
today_str = datetime.today().strftime("%Y%m%d")
output_filename = f"{today_str}_Cartesian_DL_Combos.xlsx"
cartesian_dl.to_excel(output_filename, index=False)

# Offer download in Colab
files.download(output_filename)

# ============================================================================
# Python Program End
# ============================================================================